import type { Env, Session, ActorType } from "../types";
const encoder=new TextEncoder(),ITERATIONS=210_000;type CfSubtle=SubtleCrypto&{timingSafeEqual?(a:BufferSource,b:BufferSource):boolean};
function b64(b:Uint8Array){let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s)}
function bytes(v:string){const s=atob(v);return Uint8Array.from(s,c=>c.charCodeAt(0))}
function buffer(b:Uint8Array){const c=new Uint8Array(b.byteLength);c.set(b);return c.buffer}
function safeEqual(a:ArrayBuffer,b:ArrayBuffer){if(a.byteLength!==b.byteLength)return false;const subtle=crypto.subtle as CfSubtle;if(typeof subtle.timingSafeEqual==="function")return subtle.timingSafeEqual(a,b);const x=new Uint8Array(a),y=new Uint8Array(b);let diff=0;for(let i=0;i<x.length;i++)diff|=x[i]^y[i];return diff===0}
export async function hashPassword(password:string){const salt=crypto.getRandomValues(new Uint8Array(16)),key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:buffer(salt),iterations:ITERATIONS},key,256);return `pbkdf2-sha256$${ITERATIONS}$${b64(salt)}$${b64(new Uint8Array(bits))}`}
export async function verifyPassword(password:string,stored:string){const [algorithm,it,saltText,expectedText]=stored.split("$");if(algorithm!=="pbkdf2-sha256"||!it||!saltText||!expectedText)return false;const iterations=Number(it);if(!Number.isSafeInteger(iterations)||iterations<100_000)return false;const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]),actual=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:buffer(bytes(saltText)),iterations},key,256);return safeEqual(actual,buffer(bytes(expectedText)))}
export function secureEqual(left:string,right:string){return safeEqual(buffer(encoder.encode(left)),buffer(encoder.encode(right)))}
export function randomToken(){return b64(crypto.getRandomValues(new Uint8Array(32))).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
export async function createSession(env:Env,actorType:ActorType,actorId:string):Promise<{session:Session;cookie:string}>{const session:Session={session_id:randomToken(),actor_type:actorType,actor_id:actorId,csrf_token:randomToken(),expires_at:new Date(Date.now()+7*86400_000).toISOString()};await env.DB.prepare("INSERT INTO sessions(session_id,actor_type,actor_id,csrf_token,expires_at) VALUES(?,?,?,?,?)").bind(session.session_id,actorType,actorId,session.csrf_token,session.expires_at).run();return{session,cookie:`sm_session=${session.session_id}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`}}
export async function getSession(request:Request,env:Env,expected?:ActorType):Promise<Session|null>{const match=request.headers.get("Cookie")?.match(/(?:^|;\s*)sm_session=([^;]+)/);if(!match?.[1])return null;const session=await env.DB.prepare("SELECT session_id,actor_type,actor_id,csrf_token,expires_at FROM sessions WHERE session_id=? AND expires_at>CURRENT_TIMESTAMP").bind(match[1]).first<Session>();return!session||(expected&&session.actor_type!==expected)?null:session}
export function requireCsrf(request:Request,session:Session){return request.headers.get("X-CSRF-Token")===session.csrf_token}
export function clearSessionCookie(){return"sm_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0"}
